INSERT INTO banks(name, url, isParse) VALUES ('Сбербанк', 'www.sberbank.ru', TRUE);
INSERT INTO banks(name, url, isParse) VALUES ('Банк ВТБ', 'www.vtb.ru', TRUE);
INSERT INTO banks(name, url, isParse) VALUES ('Газпромбанк', 'www.gazprombank.ru', TRUE);
INSERT INTO banks(name, url, isParse) VALUES ('Россельхозбанк', 'www.rshb.ru', TRUE);
INSERT INTO banks(name, url, isParse) VALUES ('Национальный клиринговый центр', 'www.nkcbank.ru', TRUE);
INSERT INTO banks(name, url, isParse) VALUES ('Альфа-Банк', 'www.alfabank.ru', TRUE);
INSERT INTO banks(name, url, isParse) VALUES ('Московский Кредитный Банк', 'www.mkb.ru', TRUE);
INSERT INTO banks(name, url, isParse) VALUES ('Банк Открытие', 'www.openbank.ru', TRUE);
INSERT INTO banks(name, url, isParse) VALUES ('Национальный Банк Траст', 'www.trust.ru', TRUE);
INSERT INTO banks(name, url, isParse) VALUES ('ЮниКредит Банк', 'www.unicreditbank.ru', TRUE);
INSERT INTO banks(name, url, isParse) VALUES ('Райффайзенбанк', 'www.raiffeisen.ru', TRUE);
INSERT INTO banks(name, url, isParse) VALUES ('Росбанк', 'www.rosbank.ru', TRUE);
INSERT INTO banks(name, url, isParse) VALUES ('Банк Россия', 'abr.ru', TRUE);
INSERT INTO banks(name, url, isParse) VALUES ('Совкомбанк', 'www.sovcombank.ru', TRUE);
INSERT INTO banks(name, url, isParse) VALUES ('Бинбанк', 'www.binbank.ru', TRUE);
INSERT INTO banks(name, url, isParse) VALUES ('Всероссийский Банк Развития Регионов', 'www.vbrr.ru', TRUE);
INSERT INTO banks(name, url, isParse) VALUES ('Банк Санкт-Петербург', 'www.bspb.ru', TRUE);
INSERT INTO banks(name, url, isParse) VALUES ('БМ-Банк', 'www.bm-bank.ru', TRUE);
INSERT INTO banks(name, url, isParse) VALUES ('Московский Областной Банк', 'www.mosoblbank.ru', TRUE);
INSERT INTO banks(name, url, isParse) VALUES ('Ситибанк', 'www.citibank.ru', TRUE);

INSERT INTO currencies(currency) VALUES ('USD');
INSERT INTO currencies(currency) VALUES ('EUR');
INSERT INTO currencies(currency) VALUES ('GBR');
INSERT INTO currencies(currency) VALUES ('CHF');
INSERT INTO currencies(currency) VALUES ('CNY');
INSERT INTO currencies(currency) VALUES ('JPY');